/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;

public class App {
    public static void main(String[] args) {
        TaskOne.showTask(100);
        TaskTwo.showTask(100);
        TaskThree.showTask();
        TaskFour.showTask("One two free one four ONE five FiVe zero six eleven NINE ten twelve sIx nine zero five eight OnE");
        final HashMap<String, Integer> taskFiveMap = new HashMap<>();
        taskFiveMap.put("Key", 0);
        taskFiveMap.put("AnotherKey", 1);
        taskFiveMap.put("Word", 2);
        taskFiveMap.put("String", 3);
        taskFiveMap.put("Ball", -10);
        taskFiveMap.put("Map", 1234);
        TaskFive.showTask(taskFiveMap);
    }
}
